### ISSUE TITLE
KVB and TVM signals not drawn

### ISSUE THREAD

**Issue by Sovxx** [OpenRailwayMap/OpenRailwayMap-CartoCSS#70]
https://github.com/OpenRailwayMap/OpenRailwayMap/pull/697
was not enough to draw the colored lines in the map.

**Comment by DerDakon** [comment]
When it has ETCS that is drawn and all other systems are ignored.

**Comment by STemplar** [comment]
Is this a problem? The mentioning of "railway:tvm"=300 and "railway:tvm"=430? I don't think this is needed. But I am no programmer.
![afbeelding](https://user-images.githubusercontent.com/23719607/161615205-c1c0bb8f-49c4-4d0e-af88-19b9c5d39ab6.png)

**Comment by STemplar** [comment]
> When it has ETCS that is drawn and all other systems are ignored.

Yes, but it doesn't say "railway:etcs"=yes, it says "railway:etcs"=2.

**Comment by DerDakon** [comment]
That code is the legend, i.e. this are the pseudo-tracks that are rendered to show the different styles in the legend. It has nothing to do with the actual rendering code.

**Comment by davide84** [comment]
https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/81 should fix this issue :)

**Comment by besentv** [comment]
Rendering is still not working properly when zoomed out too much.
![image](https://user-images.githubusercontent.com/10588728/197527907-36791aff-5904-463b-870e-04b190398513.png)

![image](https://user-images.githubusercontent.com/10588728/197528054-9e4b1942-832b-4e2c-8e6b-52dcbf6371cb.png)

**Comment by davide84** [comment]
Is it the website? Then it's likely not a coding issue, the online tiles take days, even weeks before being updated.
As far as I understand, only the most zoomed tiles are updated daily, or almost daily.

Also Italy should have way more pink lines than it has.

**Comment by Nakaner** [comment]
On https://tiles.openrailwaymap.org/#osm.org/9/50.366489/3.705139&overlays=signals you can right-click on a map tile and query when it was rendered the last time.

Zoom level 10 to 19 is put into rerendering queue at each data update which changed something in the tile. Zom level 0 to 9 is put into the queue every 30 days at a very low priority.
